Enum user_role {
    empleado
    cliente
}

Table sucursal {
    id_sucursal int [pk]
    nombre_sucursal varchar(100) [not null]
    direccion varchar(50) [not null]
}

Table usuario {
    id_usuario int [pk]
    id_sucursal int [ref: > sucursal.id_sucursal]
    nombre_empleado varchar(50) [not null]
    cargo varchar(50) [not null]
    username varchar(50) [not null, unique]
    password varchar(255) [not null]
    email varchar(100) [unique, not null]
    role user_role [not null]
}

Table cuenta {
    id_cuenta int [pk]
    id_usuario int [ref: > usuario.id_usuario]
    saldo decimal(12,2)
    fecha_creacion timestamp [default: `current_timestamp`]
}

Table transaccion {
    id_transaccion int [pk]
    id_cuenta int [ref: > cuenta.id_cuenta]
    fecha timestamp [default: `current_timestamp`]
    monto decimal(12,2)
    tipo_transaccion varchar(50) [not null]
    
}

Table tarjeta {
    id_tarjeta int [pk]
    id_cuenta int [ref: > cuenta.id_cuenta]
    tipo_tarjeta varchar(50) [not null]
    fecha_vencimiento date

}

Table retiro {
    id_retiro int [pk]
    id_cuenta int [ref: > cuenta.id_cuenta]
    monto decimal(12,2) [not null]
    fecha_retiro datetime
}
